[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lvlh_functions"
version = "1.0.0"
description = "functions for LV modeling with life stages, and analysis of model"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib"

]

[tool.setuptools.packages.find]
where = ["."]
include = ["lvlh_functions*"]